#I X^2
print('I')
print('','x^2_operation','',sep='\n')
x = int(input('Enter_x > '))
print('\n',f'result {x}^2 => ',x*x,'\n')
usless=input('ENTER_ANNY_KEY_AND_GO_NEXT- ')
#II (x+y+z)/3
print('\n')
print('II')
print('operation ==> (x+y+z)/3','\n')
x = int(input('Enter_x > '))
print('')
y = int(input('Enter_y > '))
print('')
z = int(input('Enter_z > '))
print('')
print(f'result ({x}+{y}+{z})/3 => ',round((x+y+z)/3,2),'\n')
usless=input('ENTER_ANNY_KEY_AND_GO_NEXT- ')
#III min --> days hours min
print()
print('III')
print('X_min => Y_h.Z_min')
print()
min_=int(input('ENTER_X_min --> '))
h=min_//60
min_end=min_%60
print('\n')
print(f'{min_}min in format h_min ==> {h}h {min_end}min')
days=h//24
h=h%24
print()
print(f'{days} days {h}h {min_end}min')
usless=input('ENTER_ANNY_KEY_AND_GO_NEXT- ')
#IV price
print()
print('IV','Discount_calculator',sep='\n')
print()
price_0=round(float(input('ENTER_PRICE --> ')),2)
print()
disc_0=int(input('ENTER_YOUR_DISCOUNT --> '))
disc_float_form=round(disc_0/100,2)
print()
price_disc=round(price_0-price_0*disc_float_form,2)
price_disc=f'{price_disc:,.2f}'.replace(',',' ')
price_0=f'{price_0:,.2f}'.replace(',',' ')
print(f' ! Sale ! -- {price_0} UAH -{disc_0}%' , f'You price => {price_disc} UAH',sep='\n')
print()
usless=input('ENTER_ANNY_KEY_AND_GO_NEXT- ')
#V last_number
print('VI','last_number_calculator',sep='\n')
print()
x=int(input('ENTER_INT_NUMBER --> '))
print()
print(f'FULL_NUMBER x = {x} => x%10 = {x}%10 => LAST_NUMBER --> {x%10}')
print()
usless=input('ENTER_ANNY_KEY_AND_GO_NEXT- ')
#VI Perimer_calculator
print('','VI','','Perimetr_calculator',sep='\n')
x_0=int(input('ENTET_L1_m --> '))
print()
x_1=int(input('ENTER_L2_m --> '))
print()
print('-----',f'|    | L_1 = {x_0} m     P(m) = 2*(L_1m+L_2m) => P(m) = 2*({x_0}+{x_1})(m) => P = {2*(x_0+x_1)}(m)','-----',f'L_2 = {x_1} m',sep='\n')
usless=input('ENTER_ANNY_KEY_AND_GO_NEXT- ')
#VII.I 4 numbers '\n'
print()
print('VII.I','SEP_4_NOMBERS',sep='\n')
print()
numb_4 = int(input(' enter_4_numbers - '))
x = numb_4//1000
y = numb_4//100-(numb_4//1000)*10
z = numb_4//10-(numb_4//100)*10
j = numb_4-(numb_4//10)*10
print(f'Numbrer_4 -- {numb_4}',f'x={numb_4}//1000 => {x}',sep='\n')
usless=input('ENTER_ANNY_KEY_AND_GO_NEXT- ')
print(f'y={numb_4}//100-({numb_4}//1000)*10 => y={numb_4//100}-{(numb_4//1000)*10} => {y}')
usless=input('ENTER_ANNY_KEY_AND_GO_NEXT- ')
print(f'z={numb_4}//10-({numb_4}//100)*10 => z={numb_4//10}-{(numb_4//100)*10} => {z}')
usless=input('ENTER_ANNY_KEY_AND_GO_NEXT- ')
print(f'j={numb_4}-({numb_4}//10)*10 => j={numb_4}-{(numb_4//10)*10} => {j}')
usless=input('ENTER_ANNY_KEY_AND_GO_RESULT- ')
print()
print('RESULT')
print(x,y,z,j,sep='\n')
usless=input('ENTER_ANNY_KEY_AND_GO_NEXT- ')
#VII.II
print('','VII.II','SEP_4_NOMBERS_USE_DIVMOD_METOD',sep='\n')
print()
numb_4 = int(input('enter_4_numbers - '))
i , k = divmod(numb_4,100)
x , y = divmod(i,10)
z , j = divmod(k,10)
print(f'divmod(m,n)=> i=m//n and k =m%n',f'number = {numb_4} => divmod({numb_4},100) => i = {i} , k = {k}',f'divmod({i},10) --> x={x} , y={y}',f'divmod({k},10) --> z={z} , j={j}',sep='\n') 
usless=input('ENTER_ANNY_KEY_AND_GO_RESULT- ')
print()
print('RESULT')
print(x,y,z,j,sep='\n')
usless=input('ENTER_ANNY_KEY_FOR_END - ')
